version: '3'

services:
  glider-dac-providers-app: &provider_anchor
    container_name: glider-dac-providers-app
    image: cgdac:latest
    restart: always
    build: .
    user: root
    ports:
      - 127.0.0.1:3000:5000
    volumes:
      - ./glider_dac_watchdog.py:/glider-dac/glider_dac_watchdog.py
      - ./config.local.yml:/glider-dac/config.local.yml
      - ../../resource/userDB/users.db:/glider-dac/users.db
      - /data:/data
      - ./erddap/:/glider-dac/erddap
      - ./dac_backend/:/glider-dac/dac_backend
    depends_on:
      - postgres

  glider-dac-datasets-xml-worker:
    <<: *provider_anchor
    image: cgdac:latest
    container_name: glider-dac-datasets-xml-worker
    command: tail -f /dev/null
    ports: [ ]
    depends_on:
      - postgres

  glider-dac-compliance-checker-worker:
    <<: *provider_anchor
    image: cgdac:latest
    container_name: glider-dac-compliance-checker-worker
    command: tail -f /dev/null
    ports: [ ]
    volumes:
      - ./config.local.yml:/glider-dac/config.local.yml
      - ./users.db:/glider-dac/users.db
      - /data:/data
    depends_on:
      - postgres

  glider-dac-watchdog:
    <<: *provider_anchor
    container_name: glider-dac-watchdog
    command: python glider_dac_watchdog.py
    image: cgdac:latest
    ports: [ ]
    environment:
      - DATA_ROOT=/data/cgdac/data_root
      - FLAGS_DIR=/data/erddapData/hardFlag
    depends_on:
      - postgres

  erddap:
    container_name: "cgdac_erddap"
    image: axiom/docker-erddap:2.22-jdk17-openjdk
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
      - 127.0.0.1:8443:8443
    environment:
      ERDDAP_MIN_MEMORY: 8G
      ERDDAP_MAX_MEMORY: 16G
    volumes:
      - "${PWD}/erddap/conf/config.sh:/usr/local/tomcat/bin/config.sh"
      - "${PWD}/erddap/conf/server.default.xml:/usr/local/tomcat/conf/server.default.xml"
      - "${PWD}/erddap/content/setup.default.xml:/usr/local/tomcat/content/erddap/setup.default.xml"
      - "${PWD}/erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt"
      - "/data/erddapData/content/datasets.default.xml:/usr/local/tomcat/content/erddap/datasets.default.xml"
      - "/data/erddapData/:/erddapData"
      - "/tmp/:/usr/local/tomcat/temp/"
      - "/data/cgdac/data_root:/data/cgdac/data_root"

  postgres:
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: glider_dac
    volumes:
      - postgres_storage:/var/lib/postgresql/data

volumes:
  thredds_cache:
  thredds_logs:
  postgres_storage:
