name: cgdac
channels:
  - conda-forge
  - anaconda
dependencies:
- Flask
- pip
- multidict
- gunicorn
- bsddb3
- python-dotenv
- cf-units
- pip:
  - Flask-Login
  - flasgger
  - Flask-WTF
  - flask_session
  - flask_migrate
  - psycopg2-binary
  - dateutils
  - flask_restx
  - flask_cors
  - passlib
