services:

  erddap:
    image: axiom/docker-erddap:${DOCKER_VERSION}
    restart: unless-stopped
    ports:
      - "127.0.0.1:${ERDDAP_PORT}:8080"
    volumes:
      - ../erddap_section/erddap/conf/server.default.xml:/usr/local/tomcat/conf/server.xml
      - ../erddap_section/erddap/conf/robots.txt:/usr/local/tomcat/webapps/ROOT/robots.txt
      - ../erddap_section/erddap/content/setup.default.xml:/usr/local/tomcat/content/erddap/setup.xml
      - ${ERDDAP_DATASETS_XML}:/usr/local/tomcat/content/erddap/datasets.xml
      - ${ERDDAP_ERDDAP_DATA}:/erddapData
      - ${ERDDAP_DATASET}:/data/cgdac/data_root
    environment:
      #note: these can also be set in /usr/local/tomcat/bin/config.sh
      ERDDAP_MIN_MEMORY: ${ERDDAP_MIN_MEMORY}
      ERDDAP_MAX_MEMORY: ${ERDDAP_MAX_MEMORY}
      ERDDAP_bigParentDirectory: /erddapData/
      ERDDAP_baseUrl: ${ERDDAP_HOST}
      ERDDAP_baseHttpsUrl: ${ERDDAP_HOST_HTTPS}
      ERDDAP_flagKeyKey: ${ERDDAP_FLAG_KEY}
      ERDDAP_emailEverythingT: ${ERDDAP_emailEverythingTo}
      ERDDAP_emailDailyReportsTo: ${ERDDAP_emailDailyReportsTo}
      ERDDAP_emailFromAddress: ${ERDDAP_emailFromAddress}
      ERDDAP_emailUserName: ${ERDDAP_emailUserName}
      ERDDAP_emailPassword: ${ERDDAP_emailPassword}
      ERDDAP_emailProperties: ${ERDDAP_emailProperties}
      ERDDAP_emailSmtpHost: ${ERDDAP_emailSmtpHost}
      ERDDAP_emailSmtpPort: ${ERDDAP_emailSmtpPort}
      ERDDAP_adminInstitution: ${ERDDAP_adminInstitution}
      ERDDAP_adminInstitutionUrl: ${ERDDAP_adminInstitutionUrl}
      ERDDAP_adminIndividualName: ${ERDDAP_adminIndividualName}
      ERDDAP_adminPosition: ${ERDDAP_adminPosition}
      ERDDAP_adminPhone: ${ERDDAP_adminPhone}
      ERDDAP_adminAddress: ${ERDDAP_adminAddress}
      ERDDAP_adminCity: ${ERDDAP_adminCity}
      ERDDAP_adminStateOrProvince: ${ERDDAP_adminStateOrProvince}
      ERDDAP_adminPostalCode: ${ERDDAP_adminPostalCode}
      ERDDAP_adminCountry: ${ERDDAP_adminCountry}
      ERDDAP_adminEmail: ${ERDDAP_adminEmail}

  postgres:
    image: postgres:16
    ports:
      - 127.0.0.1:5432:5432
    restart: always
    container_name: cgdac_postgres
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: glider_dac
    volumes:
      - postgres_storage:/var/lib/postgresql/data

  cgdac:
    container_name: cgdac
    image: cgdac:latest
    build:
      context: ..
      dockerfile: docker/Dockerfile
    user: root
    volumes:
      - socket_folder:/var/run/socket
      - ${RESOURCE_DIR}/var:/var/www
      - ${RESOURCE_DIR}/media:/home/cgdac/resource/cgdac/media
      - ${RESOURCE_DIR}/log:/home/cgdac/resource/cgdac/log
      - ${RESOURCE_DIR}/uploads:/home/cgdac/resource/cgdac/uploads
      - ${RESOURCE_DIR}:/home/cgdac/resource/cgdac/
      - ${ERDDAP_DATASET}:/home/cgdac/resource/cgdac/data
    depends_on:
      - postgres

  nginx:
    image: nginx:1.25
    ports:
      - "80:80"
    depends_on:
      - cgdac
    volumes:
      - socket_folder:/var/run/socket
      - ./nginx-conf:/etc/nginx/conf.d
      - ${RESOURCE_DIR}/nginx_log:/var/log/nginx
      - ${RESOURCE_DIR}/var/:/var/www/

volumes:
  postgres_storage:
  socket_folder: