ERDDAP_bigParentDirectory="/erddapData/"
ERDDAP_baseUrl="http://cgdac.ca"
ERDDAP_baseHttpsUrl="https://cgdac.ca"
ERDDAP_flagKeyKey="4a0c345f-d494-4edc-b8c7-640c6d99f4b1"

ERDDAP_emailEverythingTo="this+goes+nowhere@doesnotexist.ioos.us"
ERDDAP_emailDailyReportsTo=""
ERDDAP_emailFromAddress=""
ERDDAP_emailUserName=""
ERDDAP_emailPassword=""
ERDDAP_emailProperties=""
ERDDAP_emailSmtpHost=""
ERDDAP_emailSmtpPort=""

ERDDAP_adminInstitution="Coastal Environmental Observation Technology and Research (CEOTR)"
ERDDAP_adminInstitutionUrl="https://data.ceotr.ca/erddap/index.html"
ERDDAP_adminIndividualName="Sean Ling"
ERDDAP_adminPosition="Data Manager"
ERDDAP_adminPhone="240-533-9441"
ERDDAP_adminAddress="1355 Oxford St, Halifax, NS B3H 3Z1 3nd Floor"
ERDDAP_adminCity="Halifax"
ERDDAP_adminStateOrProvince="NS"
ERDDAP_adminPostalCode="B3H 3Z1"
ERDDAP_adminCountry="CA"
ERDDAP_adminEmail="info@ceotr.ca"
